---
devices:
  - vid: 6127
    pid: 24647
    macros:
      - key: "B"
        description: "Will run Ctrl+Alt+Delete"
        shortcut: 
          keys:
            - "ControlLeft"
            - "Alt"
            - "Delete"
      - key: "F"
        description: "Runs format code in VSCode"
        shortcut:
          keys:
            - "ControlLeft"
            - "ShiftLeft"
            - "I"
      - key: "W"
        description: "Open gnome-terminal"
        shell:
          uid: 1000 # only on linux
          command: "gnome-terminal"
          args: []
          envs:
            DISPLAY: ":0"
            HOME: /home/martin/