---
devices:
  - vid: 6127
    pid: 24647
    macros:
      - key: "B"
        description: "Will run Ctrl+Alt+Delete"
        shortcut: 
          keys:
            - "ControlLeft"
            - "Alt"
            - "Delete"
      - key: "F"
        description: "Runs format code in VSCode"
        shortcut:
          keys:
            - "ControlLeft"
            - "ShiftLeft"
            - "I"
      - key: "W"
        description: "Chromium"
        shell:
          uid: 1000 # Only available in Unix/Linux
          command: "chromium"
          args: []